language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
  - sudo apt-get update > /dev/null

install:
  - sudo apt-get install -y

before_script:
  - composer install --dev
  - ./app/console doctrine:database:create --env=test
  - ./app/console doctrine:schema:create --env=test
  - ./app/console doctrine:fixtures:load --no-interaction --env=test

script: ./bin/phpunit -c app/ --coverage-text

notifications:
  email:
    - jean.julien.re@gmail.com

services:
  - mysql
