language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_install:
  - sudo apt-get update > /dev/null

install:
  - sudo apt-get install -y

before_script:
  - composer install --dev

script: ./bin/phpunit -c app/ --coverage-text

notifications:
  email:
    - jean.julien.re@gmail.com
