<?php

namespace Rukien\BulletJournalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
  public function getUsersSummary($id = 0)
  {
    // @TODO there must be a way to improve the query to only get the nth user tasks
    // where the due date is the nearest using only one query
    $dql = 'SELECT 
      partial u.{user_id, username, email}, 
      partial t.{task_id, title, summary, due_date, created_at, updated_at, done, priority} 
      FROM RukienBulletJournalBundle:User u JOIN u.tasks t';
    if($id != 0)
      $dql .= ' WHERE u.user_id = :user_id';
    $query =$this->getEntityManager()
    ->createQuery($dql);

    if($id != 0)
      $query->setParameter('user_id', $id);

    return $query->getResult();
  }
}
